begin;

create extension if not exists pgcrypto;
create table if not exists hr_departments (id uuid primary key default gen_random_uuid(), name varchar(120) not null unique, code varchar(30) not null unique, active boolean not null default true, deleted_at timestamptz);
create table if not exists hr_designations (id uuid primary key default gen_random_uuid(), department_id uuid references hr_departments(id), name varchar(120) not null, active boolean not null default true, deleted_at timestamptz, unique(department_id,name));
create table if not exists hr_employees (id uuid primary key default gen_random_uuid(), employee_code varchar(30) not null unique, full_name varchar(160) not null, email varchar(254) unique, department_id uuid references hr_departments(id), designation_id uuid references hr_designations(id), reporting_manager_id uuid references hr_employees(id), joining_date date not null, employment_status varchar(30) not null default 'Active', work_location varchar(160), profile_data jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create index if not exists hr_employees_department_idx on hr_employees(department_id) where deleted_at is null;
create table if not exists hr_accounts (employee_id uuid primary key references hr_employees(id), password_hash text not null, role varchar(40) not null default 'Employee', login_enabled boolean not null default false, account_locked boolean not null default false, force_password_change boolean not null default true, failed_attempts integer not null default 0 check (failed_attempts >= 0), last_login_at timestamptz, session_version integer not null default 1, updated_at timestamptz not null default now());
create table if not exists hr_sessions (id uuid primary key default gen_random_uuid(), employee_id uuid not null references hr_employees(id), token_hash text not null unique, ip_address inet, user_agent text, expires_at timestamptz not null, revoked_at timestamptz, created_at timestamptz not null default now());
create index if not exists hr_sessions_employee_idx on hr_sessions(employee_id, expires_at);
create table if not exists hr_leave_policies (id uuid primary key default gen_random_uuid(), name varchar(120) not null, leave_type varchar(60) not null, annual_credit numeric(6,2) not null default 0, rules jsonb not null default '{}', active boolean not null default true, created_at timestamptz not null default now());
create table if not exists hr_leave_ledger (id uuid primary key default gen_random_uuid(), employee_id uuid not null references hr_employees(id), leave_type varchar(60) not null, quantity numeric(6,2) not null, entry_type varchar(20) not null check(entry_type in ('Credit','Debit','Adjustment')), reference_id uuid, remarks text, created_at timestamptz not null default now());
create index if not exists hr_leave_ledger_employee_idx on hr_leave_ledger(employee_id, leave_type, created_at);
create table if not exists hr_leave_requests (id uuid primary key default gen_random_uuid(), employee_id uuid not null references hr_employees(id), leave_type varchar(60) not null, from_date date not null, to_date date not null, days numeric(6,2) not null check(days > 0), reason text not null, attachment_key text, status varchar(30) not null default 'Pending', hod_reviewed_by uuid references hr_employees(id), hod_reviewed_at timestamptz, hr_reviewed_by uuid references hr_employees(id), hr_reviewed_at timestamptz, remarks text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(to_date >= from_date));
create index if not exists hr_leave_requests_queue_idx on hr_leave_requests(status, employee_id, from_date);
create table if not exists hr_workflow_records (id uuid primary key default gen_random_uuid(), module varchar(80) not null, employee_id uuid references hr_employees(id), title varchar(160) not null, description text, effective_date date, amount numeric(14,2), status varchar(40) not null default 'Draft', payload jsonb not null default '{}', created_by text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create index if not exists hr_workflow_records_module_idx on hr_workflow_records(module,status,updated_at desc) where deleted_at is null;
create table if not exists hr_salary_structures (id uuid primary key default gen_random_uuid(), employee_id uuid not null references hr_employees(id), effective_from date not null, annual_ctc numeric(14,2) not null check(annual_ctc >= 0), components jsonb not null, approval_status varchar(30) not null default 'Draft', approved_by text, approved_at timestamptz, created_at timestamptz not null default now());
create table if not exists hr_payroll_runs (id uuid primary key default gen_random_uuid(), payroll_year integer not null, payroll_month integer not null check(payroll_month between 1 and 12), status varchar(30) not null default 'Draft', locked_at timestamptz, locked_by text, published_at timestamptz, totals jsonb not null default '{}', created_at timestamptz not null default now(), unique(payroll_year,payroll_month));
create table if not exists hr_salary_slips (id uuid primary key default gen_random_uuid(), payroll_run_id uuid not null references hr_payroll_runs(id), employee_id uuid not null references hr_employees(id), earnings jsonb not null, deductions jsonb not null, gross numeric(14,2) not null, total_deductions numeric(14,2) not null, net_pay numeric(14,2) not null, pdf_storage_key text, published_at timestamptz, created_at timestamptz not null default now(), unique(payroll_run_id,employee_id));
create table if not exists hr_documents (id uuid primary key default gen_random_uuid(), employee_id uuid not null references hr_employees(id), document_type varchar(80) not null, financial_year varchar(12), version integer not null default 1, storage_key text not null, original_name text not null, mime_type varchar(120) not null, published_at timestamptz, downloaded_at timestamptz, created_by text not null, created_at timestamptz not null default now(), deleted_at timestamptz);
create index if not exists hr_documents_employee_idx on hr_documents(employee_id,document_type,financial_year) where deleted_at is null;
create table if not exists hr_notifications (id uuid primary key default gen_random_uuid(), employee_id uuid references hr_employees(id), role varchar(40), title varchar(180) not null, message text not null, link text, read_at timestamptz, created_at timestamptz not null default now());
create index if not exists hr_notifications_recipient_idx on hr_notifications(employee_id,read_at,created_at desc);
create table if not exists hr_audit_logs (id bigserial primary key, actor_type varchar(30) not null, actor_id text not null, action varchar(100) not null, entity_type varchar(80) not null, entity_id text, before_data jsonb, after_data jsonb, ip_address inet, created_at timestamptz not null default now());
create index if not exists hr_audit_logs_entity_idx on hr_audit_logs(entity_type,entity_id,created_at desc);

commit;
